if (!IsMounted("cstrike")) then return end
game.AddAmmoType({name = "12 Gauge", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = "9mm Parabellum", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = "7.62x51mm NATO", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = "5.7×28mm", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = "5.56x45mm NATO", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = ".50 Action Express", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = ".45 ACP", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = ".357 SIG", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
game.AddAmmoType({name = ".338 Lapua Magnum", dmgtype = DMG_BULLET, tracer = TRACER_NONE, minsplash = 10, maxsplash = 5})
list.Add("NPCUsableWeapons", {class = "ak47", title = "CV-47"})
list.Add("NPCUsableWeapons", {class = "aug", title = "Bullpup"})
list.Add("NPCUsableWeapons", {class = "awp", title = "Magnum Sniper Rifle"})
list.Add("NPCUsableWeapons", {class = "deagle", title = "Night Hawk .50c"})
list.Add("NPCUsableWeapons", {class = "elites", title = ".40 Dual Elites"})
list.Add("NPCUsableWeapons", {class = "famas", title = "Clarion 5.56"})
list.Add("NPCUsableWeapons", {class = "fiveseven", title = "ES Five-seven"})
list.Add("NPCUsableWeapons", {class = "g3sg1", title = "D3/AU-1"})
list.Add("NPCUsableWeapons", {class = "galil", title = "IDF Defender"})
list.Add("NPCUsableWeapons", {class = "glock18", title = "9x19mm Sidearm"})
list.Add("NPCUsableWeapons", {class = "m3", title = "Leone 12 Gauge Super"})
list.Add("NPCUsableWeapons", {class = "m4a1", title = "Maverick M4A1 Carbine"})
list.Add("NPCUsableWeapons", {class = "m249", title = "M249"})
list.Add("NPCUsableWeapons", {class = "mac10", title = "MAC-10"})
list.Add("NPCUsableWeapons", {class = "mp5", title = "K&M Sub-Machine Gun"})
list.Add("NPCUsableWeapons", {class = "p90", title = "ES C90"})
list.Add("NPCUsableWeapons", {class = "p228", title = "228 Compact"})
list.Add("NPCUsableWeapons", {class = "scout", title = "Schmidt Scout"})
list.Add("NPCUsableWeapons", {class = "sg550", title = "Krieg 550 Commando"})
list.Add("NPCUsableWeapons", {class = "sg552", title = "Krieg 552"})
list.Add("NPCUsableWeapons", {class = "tmp", title = "Schmidt Machine Pistol"})
list.Add("NPCUsableWeapons", {class = "ump45", title = "KM UMP45"})
list.Add("NPCUsableWeapons", {class = "usp45", title = "KM .45 Tactical"})
list.Add("NPCUsableWeapons", {class = "xm1014", title = "Leone YG1265 Auto Shotgun"})